rockons = \
          {u'OpenVPN': {u'containers': {u'openvpn': {u'image': u'kylemanna/openvpn',
                                                     u'opts': {u'cap-add': u'NET_ADMIN'},
                                                     u'ports': {u'1194': u'udp'}},
                                        u'ovpn-data': {u'image': u'busybox',
                                                       u'opts': {u'-v': u'/etc/openvpn'}}},
                        u'custom_config': {u'servername': u'Your vpn server domainname or ip address. This is the server endpoint clients will try to connect. eg: vpn.rockstor.com'},
                        u'description': u'Open Source VPN',
                        u'website': u'https://openvpn.net/'},
           u'Plex': {u'app_link': u'web',
                     u'containers': {u'plex': {u'image': u'timhaak/plex',
                                               u'opts': {u'net': u'host'},
                                               u'ports': {u'32400': u'ui'},
                                               u'volumes': [u'/config', '/data',]}},
                     u'custom_config': {u'iprange': u'ip range of your network'},
                     u'description': u'Plex media server',
                     u'website': u'https://plex.tv/'},
           'Transmission': {'app_link': '',
                            'containers': {'transmission': {'image': 'dperson/transmission',
                                                            'ports': {'9091': 'ui',
                                                                      '51413': ''},
                                                            'volumes': ['/var/lib/transmission-daemon/downloads',
                                                                        '/var/lib/transmission-daemon/incomplete',]}},
                            'custom_config': {'TRUSER': 'Set the username for your Transmission UI',
                                              'TRPASSWD': 'Password for the user'},
                            'description': 'Open Source BitTorrent client',
                            'website': 'http://www.transmissionbt.com/'},
           'BTSync': {'app_link': '',
                      'containers': {'btsync': {'image': 'aostanin/btsync',
                                                'ports': {'8888': 'ui'},
                                                'volumes': ['/data']}},
                      'description': 'BitTorrent Sync',
                      'website': 'https://www.getsync.com/'},
           'Syncthing': {'app_link': '',
                         'containers': {'syncthing': {'image': 'istepanov/syncthing',
                                                      'ports': {'8080': 'ui',
                                                                '22000': '',
                                                                '21025': 'udp'},
                                                      'volumes': ['/home/syncthing/.config/syncthing',
                                                                  '/home/syncthing/Sync',]}},
                         'description': 'Continuous File Synchronization',
                         'website': 'https://syncthing.net/',},
           'OwnCloud': {'ui': {'slug': '',
                                'https': True,},
                        'containers': {'owncloud': {'image': 'pschmitt/owncloud',
                                                    'ports': {'443': {'ui': True,
                                                                      'default': 8080,
                                                                      'protocol': 'tcp',
                                                                      'label': 'UI port',
                                                                      'description': 'OwnCloud UI port. Since Rockstor WebUI runs on 443, choose a different port or the suggested default.',},},
                                                    'volumes': {'/var/www/owncloud/data':
                                                                {'description': 'Choose a dedicated Share for OwnCloud data. Eg: create a Share called owncloud-data for this purpose alone.',
                                                                 'min_size': 1073741824,
                                                                 'label': 'Data directory',},
                                                                '/var/www/owncloud/config':
                                                                {'description': 'Choose a dedicated Share for OwnCloud configuration. Eg: create a Share called owncloud-config for this purpose alone.',
                                                                 'label': 'Config directory',
                                                                 'min_size': 1073741824,},},
                                                    'launch_order': 2,},
                                       'owncloud-postgres': {'image': 'postgres',
                                                             'volumes': {'/var/lib/pgsql/data':
                                                                         {'description': 'Choose a dedicated Share for OwnClouds postgresql database. Eg: create a Share called owncloud-db for this purpose alone.',
                                                                          'label': 'Database',
                                                                          'min_size': 1073741824, }, },
                                                             'launch_order': 1}, },
                        'container_links': {'owncloud': [{'source_container': 'owncloud-postgres',
                                                          'name': 'db'},]},
                        'custom_config': {'db_user':
                                          {'label': 'DB User',
                                           'description': 'Choose a administrator username for the OwnCloud database.',},
                                          'db_pw':
                                          {'label': 'DB Password',
                                           'description': 'Choose a secure password for the database admin user',},},
                        'description': 'Secure file sharing and hosting',
                        'website': 'https://owncloud.org/',
                        'icon': 'https://owncloud.org/wp-content/themes/owncloudorgnew/assets/img/common/logo_owncloud.svg',},
          }

# help text for Volumes
# It is strongly recommended
