# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_manager', '0002_auto_20170216_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprobe',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('error', 'error'), ('running', 'running'), ('stopped', 'stopped')], max_length=7),
        ),
        migrations.AlterField(
            model_name='taskdefinition',
            name='task_type',
            field=models.CharField(choices=[('scrub', 'scrub'), ('snapshot', 'snapshot'), ('reboot', 'reboot'), ('shutdown', 'shutdown'), ('suspend', 'suspend'), ('custom', 'custom')], max_length=100),
        ),
    ]
