"""
Copyright (c) 2012-2014 RockStor, Inc. <http://rockstor.com>
This file is part of RockStor.

RockStor is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

RockStor is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""

# for CentOS nut systemd files are:-
# from nut package
# /usr/lib/systemd/system/nut-driver.service
# /usr/lib/systemd/system/nut-server.service
# N.B. the Type=simple so just a process start
# the nut-server requires the nut-driver and is started before:-
# from nut-client package
# /usr/lib/systemd/system/nut-monitor.service
# nut-client also contains
# /lib/systemd/system-shutdown/nutshutdown

import re
from tempfile import mkstemp
from shutil import move
import logging
logger = logging.getLogger(__name__)

NUT_CONFIG = '/etc/ups/nut.conf'
NUT_UPS_CONFIG = '/etc/ups/ups.conf'
NUT_USERS = '/etc/ups/upsd.users'
NUT_MONITOR = '/etc/ups/upsmon.conf'
RHEADER = '####BEGIN: Rockstor NUT Config####'
RHEADER2 = '####Autogenerated. Do not edit below this line####'



def configure_nut(config):
    """
    read sanitized config from input form and re-write the relevant nut config
    files
    :param config:
    :return:
    """



