#!/usr/bin/python2.7

import os

join = os.path.join
base = os.path.dirname(os.path.abspath(os.path.realpath(__file__)))
base = os.path.dirname(base)

import sys
sys.path[0:0] = [
    base,
    join(base, 'eggs/Django-1.8.16-py2.7.egg'),
    join(base, 'eggs/URLObject-2.1.1-py2.7.egg'),
    join(base, 'eggs/chardet-2.3.0-py2.7.egg'),
    join(base, 'eggs/distribute-0.7.3-py2.7.egg'),
    join(base, 'eggs/django_braces-1.8.0-py2.7.egg'),
    join(base, 'eggs/django_oauth_toolkit-0.9.0-py2.7.egg'),
    join(base, 'eggs/django_pipeline-1.6.9-py2.7.egg'),
    join(base, 'eggs/django_ztask-0.1.5-py2.7.egg'),
    join(base, 'eggs/djangorecipe-1.9-py2.7.egg'),
    join(base, 'eggs/djangorestframework-3.1.1-py2.7.egg'),
    join(base, 'eggs/gevent-1.1.2-py2.7-linux-x86_64.egg'),
    join(base, 'eggs/gevent_websocket-0.9.5-py2.7.egg'),
    join(base, 'eggs/oauthlib-1.0.1-py2.7.egg'),
    join(base, 'eggs/psutil-3.3.0-py2.7-linux-x86_64.egg'),
    join(base, 'eggs/psycogreen-1.0-py2.7.egg'),
    join(base, 'eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg'),
    join(base, 'eggs/python_engineio-1.0.3-py2.7.egg'),
    join(base, 'eggs/python_socketio-1.6.0-py2.7.egg'),
    join(base, 'eggs/pytz-2014.3-py2.7.egg'),
    join(base, 'eggs/pyzmq-15.0.0-py2.7-linux-x86_64.egg'),
    join(base, 'eggs/requests-1.1.0-py2.7.egg'),
    join(base, 'eggs/setuptools-15.2-py2.7.egg'),
    join(base, 'eggs/six-1.10.0-py2.7.egg'),
    join(base, 'eggs/zc.buildout-2.5.3-py2.7.egg'),
    join(base, 'eggs/zc.recipe.egg-2.0.3-py2.7.egg'),
    join(base, 'src'),
    join(base, 'src/rockstor'),
]

import djangorecipe.manage

if __name__ == '__main__':
    sys.exit(djangorecipe.manage.main('rockstor.settings'))
