DROP DATABASE IF EXISTS smartdb WITH (FORCE);
DROP DATABASE IF EXISTS storageadmin WITH (FORCE);
DROP ROLE IF EXISTS rocky;
CREATE ROLE rocky WITH SUPERUSER LOGIN PASSWORD 'rocky';
CREATE DATABASE storageadmin;
CREATE DATABASE smartdb;
