---
- name: Disable non-OSS repos
  zypper_repository:
    name: "{{ item }}"
    state: absent
  loop:
    - repo-non-oss
    - repo-update-non-oss
  when: ansible_facts.distribution_version != "15.1"

- name: Apply all upstream updates
  zypper:
    name: "*"
    state: latest
    update_cache: yes
    disable_recommends: yes
  when: rs_inst_update_os

- block:
  - name: Install build packages
    zypper:
      name: "{{ build_packages }}"
      state: present
      update_cache: no

  # TODO: Might help put python2 dependencies on Tumbleweed
  - name: Install pip2 packages
    command: pip2 install "{{ item }}"
    loop: "{{ rs_inst_pip2_packages }}"

  - name: Install pip3 packages
    command: pip3 install "{{ item }}"
    loop: "{{ rs_inst_pip3_packages }}"

  - name: Force Postgresql 10
    command: alternatives --set postgresql /usr/lib/postgresql10
    when:
      - "'Tumbleweed' in ansible_facts.distribution"

  when: not rs_inst_install_from_repo

- name: Install useful server admin packages
  zypper:
    name: "{{ rs_inst_useful_server_packages }}"
    state: present
    update_cache: no
  when: rs_inst_useful_server_packages is defined
