# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 17:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0014_rockon_taskid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='disk',
            managers=[
                ('attached', django.db.models.manager.Manager()),
            ],
        ),
    ]
