# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-20 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0015_auto_20210513_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emailclient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='networkconnection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='oauthapp',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='poolbalance',
            options={'get_latest_by': 'start_time'},
        ),
        migrations.AlterModelOptions(
            name='sambashare',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sftp',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tlscertificate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='updatesubscription',
            options={'ordering': ['-id']},
        ),
    ]
