# Generated by Django 2.2.28 on 2023-10-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0017_auto_20230810_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disk',
            options={'base_manager_name': 'attached'},
        ),
    ]
