# Generated by Django 5.2.8 on 2026-01-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0018_auto_20231009_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfsexportgroup',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='dcontainer',
            name='gid',
            field=models.IntegerField(null=True),
        ),
    ]
