# Generated by Django 5.2.8 on 2026-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0019_alter_nfsexportgroup_options_dcontainer_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='taskid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
